# Matugen Hyprland Colors

$background = rgb(0e1415)

$error = rgb(ffb4ab)

$error_container = rgb(93000a)

$inverse_on_surface = rgb(2b3232)

$inverse_primary = rgb(00696b)

$inverse_surface = rgb(dde4e3)

$on_background = rgb(dde4e3)

$on_error = rgb(690005)

$on_error_container = rgb(ffdad6)

$on_primary = rgb(003738)

$on_primary_container = rgb(9cf1f2)

$on_primary_fixed = rgb(002020)

$on_primary_fixed_variant = rgb(004f51)

$on_secondary = rgb(1b3435)

$on_secondary_container = rgb(cce8e8)

$on_secondary_fixed = rgb(041f20)

$on_secondary_fixed_variant = rgb(324b4b)

$on_surface = rgb(dde4e3)

$on_surface_variant = rgb(bec8c8)

$on_tertiary = rgb(1d314c)

$on_tertiary_container = rgb(d4e3ff)

$on_tertiary_fixed = rgb(051c35)

$on_tertiary_fixed_variant = rgb(344863)

$outline = rgb(899392)

$outline_variant = rgb(3f4949)

$primary = rgb(80d4d6)

$primary_container = rgb(004f51)

$primary_fixed = rgb(9cf1f2)

$primary_fixed_dim = rgb(80d4d6)

$scrim = rgb(000000)

$secondary = rgb(b0cccc)

$secondary_container = rgb(324b4b)

$secondary_fixed = rgb(cce8e8)

$secondary_fixed_dim = rgb(b0cccc)

$shadow = rgb(000000)

$source_color = rgb(586666)

$surface = rgb(0e1415)

$surface_bright = rgb(343a3a)

$surface_container = rgb(1a2121)

$surface_container_high = rgb(252b2b)

$surface_container_highest = rgb(2f3636)

$surface_container_low = rgb(161d1d)

$surface_container_lowest = rgb(090f0f)

$surface_dim = rgb(0e1415)

$surface_tint = rgb(80d4d6)

$surface_variant = rgb(3f4949)

$tertiary = rgb(b4c8e9)

$tertiary_container = rgb(344863)

$tertiary_fixed = rgb(d4e3ff)

$tertiary_fixed_dim = rgb(b4c8e9)

