source = ~/.config/hypr/colors.conf

background {
    monitor =
    color = $color
    path = screenshot
    blur_passes = 3
}

animations {
    enabled = true
}

input-field {
    size = 300, 100
    position = 8, 8
    halign = left
    valign = bottom

    inner_color = $background
    outer_color = $outline
    outline_thickness = 1

    font_family = Jetbrains Mono Nerd Font
    font_color = rgba(ebebebff)

    placeholder_text =   Enter password 󰆧 
    check_color = $check_color
    fail_text = <i>Wrong passowrd [$ATTEMPTS] 󱐝 </i>

    rounding = 0
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = true
}
